### ISSUE TITLE
Missing uninstallation guide

### ISSUE THREAD

**Issue by SzilvasiPeter** [mgoltzsche/podman-static#101]
First of all, thank you for providing an easier way to install `podman` CLI. The installation is simply extracting and copying the binaries into the appropriate folders, however the documentation does not provide the uninstallation steps. Here is the uninstallation steps that "reverse" the binaries copy:

```bash
sudo rm -rf /etc/containers/*
sudo rm -rf /usr/lib/systemd/system/podman*
sudo rm -rf /usr/lib/systemd/user/podman*
sudo rm -rf /usr/local/bin/{crun,fuse-overlayfs,fusermount3,pasta,pasta.avx2,podman,runc}
sudo rm -rf /usr/local/lib/podman
```

Additionally, it is also very advisable to clear all containers, images, and so on with the following command:

```bash
sudo podman system reset
```

**Comment by mgoltzsche** [comment]
Closed by #102.
