### ISSUE TITLE
Move /usr/libexec to /user/local/libexec

### ISSUE THREAD

**Issue by PhracturedBlue** [mgoltzsche/podman-static#15]
For the static-build, it would be preferable to move the cni plugins on conmon to /usr/local/libexec instead of /usr/libexec to further segregate this from files managed by the package manager.  /usr/local/libexec is already in the search path, so no additional action should be needed.

**Comment by mgoltzsche** [comment]
@PhracturedBlue makes sense!

**Comment by mgoltzsche** [comment]
Turns out that podman doesn't look for CNI plugins within `/usr/local/libexec` but expects them to be present within `/usr/libexec`. Though it also looks within `/usr/local/lib/cni`. That would be better already, wouldn't it? A PR would be welcome.

**Comment by PhracturedBlue** [comment]
Merged
