### ISSUE TITLE
Update podman to 1.3.1 / latest?

### ISSUE THREAD

**Issue by pwFoo** [mgoltzsche/podman-static#2]
I tried to update podman 1.0.0 to 1.3.1, but get an error message with my build.
```
Error: error creating libpod runtime: failed to get new shm lock manager: failed to create 2048 locks in /libpod_lock: no such file or directory
```

@mgoltzsche

**Comment by mgoltzsche** [comment]
@pwFoo I pushed an update. Should be available as 'latest' soon on docker hub. Let me know if it works for you.
(For the old image there is the v1.0 tag.)

**Comment by mgoltzsche** [comment]
@pwFoo I've added the following tags:
* `1.4.0`
* `1.3.2`
* `1.3.1`
* `1.0.0`

The version scheme `vX.X` which I temporary used is now deprecated.
