### ISSUE TITLE
missing CNI nsenter plugin

### ISSUE THREAD

**Issue by tomdavidson** [mgoltzsche/podman-static#28]
Thank you for building and sharing this.

version 3.3.1

All commands I have tried other than `-v` give me:

```
Error: error configuring CNI network plugin: exec: "nsenter": executable file not found in $PATH
```

So I need to separately install the nsenter CNI plugin?

**Comment by mgoltzsche** [comment]
nsenter is not a CNI plugin. You need to install it on your host separately.
(If you want to run podman as unprivileged user, you also need to install
uidmap - I should probably document this.)

Tom Davidson ***@***.***> schrieb am Di., 28. Sep. 2021,
08:46:

**Comment by tomdavidson** [comment]
Thank you for the quick help.
