### ISSUE TITLE
Some files are dynamically linked

### ISSUE THREAD

**Issue by Poorunga** [mgoltzsche/podman-static#3]
Some files are dynamically linked: conmon, fuse-overlayfs, fusermount3, slirp4netns

**Comment by Poorunga** [comment]
Can these binaries be statically compiled

**Comment by mgoltzsche** [comment]
@Poorunga all but fusermount3 were actually statically linked.
In `mgoltzsche/podman:1.9.0` fusermount3 is now statically linked as well.

Regarding the linking what may have confused you (confused me once):
* Within an alpine container `ldd <BINARY>` always lists musl:
```
$ docker run --rm --privileged mgoltzsche/podman:1.8.2 ldd /usr/libexec/podman/conmon
	/lib/ld-musl-x86_64.so.1 (0x7f20c0b5f000)
```
* Same binary on my Ubuntu host:
```
$ docker create --name pmtest mgoltzsche/podman:1.8.2
$ docker cp pmtest:/usr/libexec/podman/conmon conmon
$ ldd conmon
	statically linked
```
