### ISSUE TITLE
Use of podman release with AlmaLinux

### ISSUE THREAD

**Issue by srbala** [mgoltzsche/podman-static#30]
@mgoltzsche this is more of question. Is it possible to use release files with `AlmaLinux` instead of `Alpine`, what would be prereqeust packages required.

**Comment by mgoltzsche** [comment]
Since all binaries built from this repository are statically linked you should be able to copy and use them within any other Linux distribution, including AlmaLinux.

**Comment by mgoltzsche** [comment]
hm, I am not sure what the benefit is. Can you tell me your use case? If you want a RHEL kind of image you could use the official one (`quay.io/podman/stable`), couldn't you?
Also one of the ideas of maintaining this repository for me is to ship a small podman image with minimal dependencies as opposed to have 73mb overhead the almalinux container comes with.
