### ISSUE TITLE
Error: cannot setup namespace using newuidmap: exit status 1

### ISSUE THREAD

**Issue by ariansvirsky** [mgoltzsche/podman-static#36]
When trying to run it on k8s, getting the error `Error: cannot setup namespace using newuidmap: exit status 1`

**Comment by mgoltzsche** [comment]
@ariansvirsky it should work if you run podman within a privileged container - you can still let it run as unprivileged user.

**Comment by mgoltzsche** [comment]
@ariansvirsky something else came to mind: please try using the `mgoltzsche/podman:3.4.2-minimal` image. Since it does not create a user namespace in the first place the uidmap error would not occur.

**Comment by mgoltzsche** [comment]
This should have been fixed with the 4.4.2 release.
