### ISSUE TITLE
Error: no such file or directory on arm64

### ISSUE THREAD

**Issue by alex3305** [mgoltzsche/podman-static#42]
Hi 👋, 

Thanks for this great effort. I wanted to try and get podman running on my router. Yes, this is probably mad because of the limited OS and resources, but the host should comply to all minimal requirements, so why not? For this I was trying to botch together podman as an entware package, so my paths may seem a bit weird. But now I've seem to hit a wall that I cannot seem to get around.

## Installation instructions

I've whipped up some basic installation instructions to install your binaries and get them on path:

```bash
# NOTE: /tmp/mnt/router/ is an USB device which is the installation target for entware

# First we install the required packages and create the required directories
opkg install curl nsenter shadow-newuidmap
mkdir -p /tmp/mnt/router/podman
cd /tmp/mnt/router/podman/

# Then we download your podman binaries and extract them to the entware locations, which are in PATH
curl -fsSL -O https://github.com/mgoltzsche/podman-static/releases/latest/download/podman-linux-arm64.tar.gz
tar -xzf podman-linux-arm64.tar.gz
cp -r podman-linux-arm64/usr/local podman-linux-arm64/etc ../entware/

# Just a little cleanup
rm podman-linux-arm64.tar.gz
rm -f podman-linux-arm64

# Create the necessary directories and symlink everything to our USB pen drive
mkdir -p /tmp/mnt/router/podman/temp/containers/storage /tmp/mnt/router/podman/share/containers/storage /var/lib/containers/ ~/.local/share/co
ntainers/ /var/run/containers
ln -s /tmp/mnt/router/podman/share/containers/storage /var/lib/containers/storage 
ln -s /tmp/mnt/router/podman/share/containers/storage ~/.local/share/containers/storage
ln -s /tmp/mnt/router/podman/temp/containers/storage /var/run/containers/storage

# Set the correct fuse-overlayfs location in storage.json
vim /tmp/mnt/router/entware/etc/containers/storage.conf
# mount_program = "/usr/local/bin/fuse-overlayfs" > mount_program = "/tmp/mnt/router/entware/usr/bin/fuse-overlayfs"

# Optionally create an alias for podman to use as Docker
ln -s /tmp/mnt/router/entware/usr/bin/podman /tmp/mnt/router/entware/bin/docker
```

## Results?

First of all podman is found and I can get it running with `podman --version` 🥳 

```bash
admin@Router:/tmp/home/root# podman --version
podman version 4.1.1
```

But any other command will result in the same error:

```bash
admin@Router:/tmp/home/root# podman info
Error: no such file or directory
admin@Router:/tmp/home/root# podman images
Error: no such file or directory
admin@Router:/tmp/home/root# podman run --rm -it alpine /bin/sh
Error: no such file or directory
```

I guess it has something to do with the directory where images should be stored. But I'm unsure how to configure or debug this.

I would appreciatie some help in getting podman running on this very limited device. So if you can point me in the right direction that would be great. Also please feel free to use any of this as documentation if you want to. Thanks again ❤️.

**Comment by mgoltzsche** [comment]
@alex3305 it is odd that `podman --version` works but `podman info` does not.
Please try `podman --log-level=debug images`. Maybe it gives you a bit more information.
Otherwise I'd make sure that all involved binaries are actually working in your environment (I've seen such an error also when a binary doesn't work due to a missing library) by calling e.g. `<binary> --version`.

**Comment by alex3305** [comment]
Yes, it seems so:

```bash
admin@Router:/tmp/mnt/router/entware/usr/lib/podman# ./conmon --version
conmon version 2.1.2
commit: 2bc95ee697e87d5f7b77063cf83fc32739addafe
```

I looked into your Docker image on an amd64 machine and it seems that I perhaps was missing a directory:

```bash
/ $ podman --log-level trace images
INFO[0000] podman filtering at log level trace
DEBU[0000] Called images.PersistentPreRunE(podman --log-level trace images)
TRAC[0000] Reading configuration file "/etc/containers/containers.conf"
DEBU[0000] Merged system config "/etc/containers/containers.conf"
```

However symlinking `/etc/containers` to `/tmp/mnt/router/entware/etc/containers` doesn't change a thing 😢.
