### ISSUE TITLE
Is it possible to compile into a static file of ARM architecture?

### ISSUE THREAD

**Issue by xy815661276** [mgoltzsche/podman-static#5]
This Dockerfile can correctly compile static files of the X86 architecture, but I don't know if it is possible to compile it into a static file of the ARM architecture. Can you give me some suggestions?

**Comment by xy815661276** [comment]
I can successfully compile with the image of arm64v8, and I have compiled it.

**Comment by mgoltzsche** [comment]
Great to know! I didn't try that.
