### ISSUE TITLE
option for setting up podman without sudo 

### ISSUE THREAD

**Issue by ghost** [mgoltzsche/podman-static#52]
Hey, what I am trying to do is setup podman without sudo. So What I am doing step-by-step:

1. download archive: `curl -fsSL -o podman-linux-amd64.tar.gz https://github.com/mgoltzsche/podman-static/releases/latest/download/podman-linux-amd64.tar.gz`
2. unpack: `tar -xzf podman-linux-amd64.tar.gz`
3. CAN'T do this step because I do not have root / sudo: `sudo cp -r podman-linux-amd64/usr podman-linux-amd64/etc /`
4. Get the error when executing `./podman-linux-amd64/usr/local/bin/podman version`
```
Error: could not find a working conmon binary (configured options: [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon]: invalid argument)
```
is there something I can do to fix this without having sudo / root ?

**Comment by mgoltzsche** [comment]
You could copy the binaries into a different location and configure the path to those binary within [containers.conf](https://github.com/containers/common/blob/v0.51.0/pkg/config/containers.conf#L361).

**Comment by mgoltzsche** [comment]
oh and you'd need to copy your edited `containers.conf` into `~/.config/containers/containers.conf`. Similar for the other config. See [here](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md#containersconf) - I should link that page within the readme of this repo.
