### ISSUE TITLE
podman v4.6.0 released 

### ISSUE THREAD

**Issue by calvin2021y** [mgoltzsche/podman-static#64]
podman v4.6.0 released

**Comment by calvin2021y** [comment]
with your 4.5.1, get this error:

```sh
Error: could not find "netavark" in one of [/usr/local/libexec/podman /usr/local/lib/podman /usr/libexec/podman /usr/lib/podman].  To resolve this error, set the helper_binaries_dir key in the `[engine]` section of containers.conf to the directory containing your helper binaries.
```

**Comment by mgoltzsche** [comment]
My [test](https://github.com/mgoltzsche/podman-static/pull/65) of the podman 4.6.0 build works.
It would be good to add a test that makes it fail.
What's the use-case that makes you run into this error? Which podman command(s) you run?
