### ISSUE TITLE
Working with self signed registry and podman docker image

### ISSUE THREAD

**Issue by srbala** [mgoltzsche/podman-static#7]
This is a Q/A, not an issue.

Using your`mgoltzsche/podman` docker image, in Jenkin pipeline. Podman was able to access the public registries but fails on internal registry `servername:5000`. Internal registry is a `docker/registry` using self signed certificate. I have added `servername:5000` to registries.conf and using option `--add-host servername:ip-addr`, still not able to connect.

**Comment by mgoltzsche** [comment]
@srbala which error is shown in the logs?
I assume that it is failing due to the self-signed certificate. To fix that case you'd need to run podman using the `--tls-verify=false` option or sign your registry's certificate using a CA certificate that you register with podman.

**Comment by srbala** [comment]
@mgoltzsche Thank you! Passing the option `--tls-verify=false` for `login` and `push` worked.
