### ISSUE TITLE
Is the above version of podman consistent with this link(https://github.com/containers/podman/tree/v4.8.2)

### ISSUE THREAD

**Issue by fantastic2085** [mgoltzsche/podman-static#74]
Is the above version of podman consistent with this link(https://github.com/containers/podman/tree/v4.8.2)

**Comment by mgoltzsche** [comment]
When you created the issue this repo only released the 4.8.1 version of podman.
Though, now [4.8.2 has been released](https://github.com/mgoltzsche/podman-static/releases/tag/v4.8.2), corresponding to the upstream podman version you linked.
Generally, I try to let releases within this repo be in sync with the upstream podman version - a new podman-static release is usually published days or weeks after the corresponding upstream podman release.
