### ISSUE TITLE
Deploying ceph, using podman4.8.2, error messag

### ISSUE THREAD

**Issue by fantastic2085** [mgoltzsche/podman-static#79]
Deploying ceph with cephadm creates cephadm users As shown below:
![image](https://github.com/mgoltzsche/podman-static/assets/4116773/151b79ee-8998-4d1f-bb44-841ce4797bae)

However, when you use podman-static 4.8.2, you find that no cephadm user has been created

I don't know why it wasn't created

**Comment by mgoltzsche** [comment]
> I don't know why it wasn't created

Me neither. Maybe a ceph initialization script silently failed to create the user but still returned successfully due to a bug?
Can you try to get more information/logs? In case ceph doesn't log sufficient information, maybe try enabling debug logs in ceph?

**Comment by mgoltzsche** [comment]
I am closing this issue since there was no response.
Please feel free to re-open it when you have more information.
(Btw maybe things changed now with podman 5.)
