### ISSUE TITLE
Add netavark and aardvark-dns

### ISSUE THREAD

**Issue by lordwelch** [mgoltzsche/podman-static#84]
Would you be open to a PR to add netavark and aardvark-dns?

**Comment by mgoltzsche** [comment]
Sure, given that these binaries are already shipped with the official fedora-based podman image, go for it! Though, I wonder in which scenario(s) they are used with podman. So, when you create a pull request, it would be great if you'd create a corresponding e2e test(s) (just a simple CLI call within a *.bats file) to illustrate how they are used and to ensure they remain usable during subsequent updates.

**Comment by mgoltzsche** [comment]
It took a while but now this was addressed within #91: Finally the v5.1.1 release is shipped with netavark, pasta (instead of CNI and slirp4netns) and aardvark-dns.
